500Dishes/Controllers/VendorController.cs
using _500Dishes.Misc;
using _500Dishes.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using System.IO;
using System.Threading.Tasks;

namespace _500Dishes.Controllers
{
    [Authorize(Roles = "V")]
    public class VendorController : Controller
    {
        private DataContext db = new DataContext();
        private void setVendorDetails()
        {
            int userID = getSignedInUserID();
            var vendor = db.Vendors.Find(userID);
            ViewBag.VendorName = vendor.FirstName.ToLower() + " " + vendor.LastName.ToUpper();
            ViewBag.VendorBrandName = vendor.BrandName;
            ViewBag.VendorReviews = vendor.Reviews.Count;
            ViewBag.VendorImage = vendor.ImagePath;
        }
        // GET: Vendor
        public ActionResult Index()
        {
            setVendorDetails();
            return View();
        }

        public ActionResult Locations(int? page)
        {
            setVendorDetails();
            ViewBag.Locations = "active";
            int pageSize = 12;
            int pageNumber = (page ?? 1);
            string email = User.Identity.Name;
            Vendor vendor = db.Vendors.Include("DeliveryLocations").SingleOrDefault(x => x.Email == email);
            if (vendor != null)
            {
                return View(vendor.DeliveryLocations.ToPagedList(pageNumber, pageSize));
            }
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        [HttpGet]
        public ActionResult AddLocation()
        {
            setVendorDetails();
            ViewBag.Locations = "active";
            ViewBag.Location = new SelectList(db.Locations.ToList(), "LocationID", "Name");
            if (Request.IsAjaxRequest())
                return PartialView();
            else
                return View();
        }

        [HttpPost]
        public ActionResult AddLocation(int? Location)
        {
            setVendorDetails();
            ViewBag.Locations = "active";
            if (Location != null)
            {
                int vendorID = getSignedInUserID();
                VendorLocation vloc = new VendorLocation
                {
                    LocationID = Location.Value,
                    VendorID = vendorID
                };
                db.VendorsLocations.Add(vloc);
                db.SaveChanges();
                return RedirectToAction("Locations");
            }
            return RedirectToAction("Locations");
        }

        public ActionResult Meals(int? page)
        {
            setVendorDetails();
            ViewBag.Meals = "active";
            int pageSize = 12;
            int pageNumber = (page ?? 1);
            int id = getSignedInUserID();
            Vendor v = db.Vendors.Include("Meals").SingleOrDefault(x => x.VendorID == id);
            if (v != null)
                return View(v.Meals.ToPagedList(pageNumber, pageSize));

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        public ActionResult BankDetails()
        {
            setVendorDetails();
            ViewBag.BankDetails = "active";
            int id = getSignedInUserID();
            ViewBag.BankName = new SelectList(db.Banks, "ID", "Name");
            Vendor v = db.Vendors.Find(id);
            if (v != null)
                return View(new WithdrawalSettingsViewModel
                {
                    VendorID = v.VendorID,
                    AccountName = v.AccountName,
                    AccountNumber = v.AccountNumber,
                    BankName = v.BankID
                });
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        [HttpPost]
        public ActionResult BankDetails(WithdrawalSettingsViewModel settings)
        {
            setVendorDetails();
            ViewBag.BankDetails = "active";
            if (ModelState.IsValid)
                if (settings.VendorID == getSignedInUserID())
                {
                    Vendor v = db.Vendors.Find(settings.VendorID);
                    v.AccountName = settings.AccountName;
                    v.AccountNumber = settings.AccountNumber;
                    v.BankID = settings.BankName;
                    db.Entry(v).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                }
            ViewBag.BankName = new SelectList(db.Banks, "ID", "Name");
            return View(settings);
        }

        public ActionResult Transactions()
        {
            setVendorDetails();
            ViewBag.Transactions = "active";
            int id = getSignedInUserID();
            Vendor v = db.Vendors.Include("Transactions").SingleOrDefault(x => x.VendorID == id);
            TransactionsViewModel tr = new TransactionsViewModel()
            {
                VendorID = v.VendorID,
                Balance = v.AccountBalance,
                Withdrawals = (v.Transactions != null ? v.Transactions.OrderByDescending(x => x.Date).ToList() : new List<_500Dishes.Models.Transaction>())
            };
            return View(tr);
        }

        public ActionResult WithdrawEarnings()
        {
            setVendorDetails();
            ViewBag.Withdraw = "active";
            int id = getSignedInUserID();
            Vendor v = db.Vendors.Include("Bank").SingleOrDefault(x => x.VendorID == id);
            if (v != null)
                return View(new WithdrawEarningsViewModel
                {
                    VendorID = v.VendorID,
                    AccountName = v.AccountName,
                    AccountNumber = v.AccountNumber,
                    BankName = (v.Bank != null ? v.Bank.Name : "")
                });
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        [HttpPost]
        public ActionResult WithdrawEarnings(WithdrawEarningsViewModel withdrawal)
        {
            setVendorDetails();
            ViewBag.Withdraw = "active";
            if (ModelState.IsValid)
            {
                Vendor v = db.Vendors.Find(withdrawal.VendorID);
                if (v.AccountBalance >= withdrawal.Amount)
                {
                    _500Dishes.Models.Transaction w = new _500Dishes.Models.Transaction
                    {
                        Amount = withdrawal.Amount,
                        VendorID = withdrawal.VendorID,
                        ExtraText = (withdrawal.ExtraText == "") ? "--" : withdrawal.ExtraText,
                        Date = DateTime.UtcNow.AddHours(1),
                        Withdrawal = true,
                    };
                    db.Transactions.Add(w);
                    v.AccountBalance -= withdrawal.Amount;
                    db.Entry(v).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();

                    return View();
                }
                ModelState.AddModelError("", "invalid transaction. \r\namount to be withdrawn exceeds vendor balance");
            }
            return View(withdrawal);
        }

        public ActionResult AddMeal()
        {
            setVendorDetails();
            ViewBag.Meals = "active";
            return View();
        }

        [HttpPost]
        public ActionResult AddMeal(MealViewModel mvm, HttpPostedFileBase image)
        {
            setVendorDetails();
            ViewBag.Meals = "active";
            if (ModelState.IsValid)
            {
                Meal meal = new Meal()
                {
                    Name = mvm.Name,
                    Description = mvm.Description,
                    VendorID = getSignedInUserID(),
                    DateAdded = DateTime.UtcNow.AddHours(1)
                };
                if (image != null && image.ContentLength > 0 && image.ContentType.Contains("image"))
                {
                    var filePath = Guid.NewGuid().ToString("N") + "_" + Path.GetFileName(image.FileName);
                    string path = Path.Combine(HttpContext.Server.MapPath("~/Images/Meals"), filePath);
                    image.SaveAs(path);
                    meal.ImagePath = filePath;
                }
                db.Meals.Add(meal);
                db.SaveChanges();
                return RedirectToAction("Meals");
            }
            return View(mvm);
        }

        public ActionResult DeleteMeal(int? id)
        {
            setVendorDetails();
            if (id != null)
            {
                Meal meal = db.Meals.Find(id.Value);
                if (meal != null && meal.VendorID == getSignedInUserID())
                {
                    db.Entry(meal).State = System.Data.Entity.EntityState.Deleted;
                    db.SaveChanges();
                }
            }
            return RedirectToAction("Meals");
        }

        public ActionResult EditMeal(int? id)
        {
            setVendorDetails();
            ViewBag.Meals = "active";
            if (id != null)
            {
                Meal meal = db.Meals.Find(id.Value);
                if (meal != null)
                {
                    EditMealViewModel emvm = new EditMealViewModel
                    {
                        ID = meal.ID,
                        Name = meal.Name,
                        Description = meal.Description,
                        ImagePath = meal.ImagePath
                    };
                    if (Request.IsAjaxRequest())
                        return PartialView(emvm);
                    return View(emvm);
                }
            }
            return RedirectToAction("Meals");
        }

        [HttpPost]
        public ActionResult EditMeal(EditMealViewModel emvm, HttpPostedFileBase image)
        {
            setVendorDetails();
            ViewBag.Meals = "active";
            if (ModelState.IsValid)
            {

500Dishes/Views/Admin/AllCustomers.cshtml
@model PagedList.IPagedList<_500Dishes.Models.User>
@using PagedList.Mvc;


@{
    ViewBag.Title = "AllCustomers";
    Layout = "~/Views/Shared/_AdminLayoutPage.cshtml";
}

<h2>AllCustomers</h2>

@if (TempData["CustomerMessage"] != null)
{
    <div class="alert alert-danger alert-dismissable" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @TempData["CustomerMessage"].ToString()
    </div>
}

<table class="table table-responsive table-hover table-condensed">
    <tr>
        <th>Name</th>
        <th>Phone</th>
        <th>Email</th>
        <th>Address</th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>@Html.ActionLink("Select", "Customer", new { id = @item.UserID }, new { @class = "btn" })</td>
        </tr>
    }

</table>

<div class="container">
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of
    @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("AllCustomers", new { page }))
</div>

500Dishes/Views/Admin/AllMeals.cshtml
@model PagedList.IPagedList<_500Dishes.Models.Meal>
@using PagedList.Mvc

@{
    ViewBag.Title = "Meals";
    Layout = "~/Views/Shared/_AdminLayoutPage.cshtml";
}

@if (TempData["SubscriptionError"] != null)
{
    <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @(TempData["SubscriptionError"] as string)
    </div>
}
@if (TempData["MealSuccess"] != null)
{
    <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @(TempData["MealSuccess"] as string)
    </div>
}


<h2>Meals</h2>

<table class="table">
    <tr>
        <th>
            Vendor
        </th>
        <th>
            Name
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.ImagePath)
            </th>*@
        <th>
            Orders
        </th>
        <th>
            Description
        </th>
        <th>
            Verified
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @if (item.Vendor.BrandName != null)
                { @Html.DisplayFor(modelItem => item.Vendor.BrandName) }
            </td>
            <td>
                @Html.ActionLink(item.Name, "Vendor", new { id = item.ID })
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.ImagePath)
                </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.Orders.Count)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Verified)
            </td>
            @if (item.Verified == false)
            {
                <td>
                    <a href="#verify-meal" data-toggle="modal" class="btn btn-default" data-mealname="@item.Name" data-mealid="@item.ID">Verify</a>
                </td>
            }
            @*
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
                    @Html.ActionLink("Details", "Details", new { id=item.ID }) |
                    @Html.ActionLink("Delete", "Delete", new { id=item.ID })
            </td>*@
        </tr>
    }

</table>

<div class="container">
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of
    @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("AllMeals", new { page }))
</div>

<div class="modal fade" id="verify-meal" aria-hidden="true" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h2 class="modal-title text-center text-danger">Verify Meal</h2>
            </div>
            <div class="modal-body">
                <p class="text-center" id="modal-body-text">Please confirm verification of <strong><span class="meal-name"></span></strong> ?</p>
                <div id="delete-form">
                    @using (Html.BeginForm("VerifyMeal", "Admin", new { }, FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        <input type="hidden" name="id" class="meal-id">
                        <button type="submit" class="btn btn-primary text-uppercase">Submit</button>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script type="text/javascript">
        $(function () {
            $('#verify-meal').on('show.bs.modal', function (event) {
                var button = $(event.relatedTarget)
                var id = button.data('mealid')
                var name = button.data('mealname')
                /*console.log("id => "+ id)
                console.log("name => " + name)
                console.log("count => " + count)*/
                //modal.find('#subName').html(name)
                var modal = $(this)
                modal.find('.meal-id').val(id)
                modal.find('.meal-name').html(name)
            });

        });
    </script>
}

500Dishes/Views/Admin/AllVendors.cshtml
@model PagedList.IPagedList<_500Dishes.Models.Vendor>
@using PagedList.Mvc;

@{
    ViewBag.Title = "AllVendors";
    Layout = "~/Views/Shared/_AdminLayoutPage.cshtml";
}

<h2>AllVendors</h2>

@if (TempData["VendorMessage"] != null)
{
    <div class="alert alert-danger alert-dismissable" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @TempData["VendorMessage"].ToString()
    </div>
}

<table class="table table-responsive table-hover table-condensed">
    <tr>
        <th>
            Name
        </th>
        <th>
           Brand Name
        </th>
        <th>
           Phone
        </th>
        <th>
            Email
        </th>
        <th>
            Verified
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.ImagePath)
        </th>*@
        <th>
            Meal Price
        </th>
        <th></th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
                <br />
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BrandName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Verified)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.ImagePath)
            </td>*@
            @if (item.Verified == false)
            {
                <td contenteditable="true" id="price-for-@item.VendorID">
                    @Html.DisplayFor(modelItem => item.MealPrice)
                </td>
                <td>
                    @*@Html.ActionLink("Edit", "Edit", new { id=item.VendorID }) |
                        @Html.ActionLink("Details", "Details", new { id=item.VendorID }) |
                        @Html.ActionLink("Delete", "Delete", new { id=item.VendorID })*@
                    <a href="#verify-vendor" data-toggle="modal" class="btn btn-default" data-brandname="@item.BrandName" data-vendorid="@item.VendorID">Verify</a>
                </td>
            }
            else
            {
                <td contenteditable="true" id="price-for-@item.VendorID">
                    @Html.DisplayFor(modelItem => item.MealPrice)
                </td>
                <td><a href="#edit-vendor" data-toggle="modal" class="btn btn-warning" data-brandname="@item.BrandName" data-vendorid="@item.VendorID">Edit</a></td>
            }
            <td>@Html.ActionLink("Select", "Vendor", new { id = @item.VendorID }, new { @class= "btn"} )</td>
        </tr>
    }

</table>

<div class="container">
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of
    @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("AllVendors", new { page }))
</div>

<div class="modal fade" id="verify-vendor" aria-hidden="true" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h2 class="modal-title text-center text-danger">Verify Vendor</h2>
            </div>
            <div class="modal-body">
                <p class="text-center" id="modal-body-text"></p>
                <div id="delete-form">
                    @using (Html.BeginForm("VerifyVendor", "Admin", new { }, FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        <input type="hidden" name="id" class="vendor-id">
                        <input type="hidden" name="price" class="price">
                        <button type="submit" class="btn btn-primary text-uppercase">Submit</button>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="edit-vendor" aria-hidden="true" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h2 class="modal-title text-center text-danger">Verify Vendor</h2>
            </div>
            <div class="modal-body">
                <p class="text-center" id="modal-body-text"></p>
                <div id="delete-form">
                    @using (Html.BeginForm("VerifyVendor", "Admin", new { }, FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        <input type="hidden" name="id" class="vendor-id">
                        <input type="hidden" name="price" class="price">
                        <button type="submit" class="btn btn-primary text-uppercase">Submit</button>
                    }
                </div>
            </div>
        </div>
    </div>
</div>


@section scripts{
    <script type="text/javascript">
        $(function () {
            $('#verify-vendor').on('show.bs.modal', function (event) {
                var button = $(event.relatedTarget)
                var id = button.data('vendorid')
                var name = button.data('brandname')
                var price = $('#price-for-' + id).html()
                //console.log('price => ' + price)
                //console.log("name => " + name)
                /*console.log("id => "+ id)
                console.log("name => " + name)
                console.log("count => " + count)*/
                //modal.find('#subName').html(name)
                var modal = $(this)
                if (price > 100) {
                    modal.find('#modal-body-text').html("Are you sure you would like to submit changes for <strong>" + name + "</strong> ?")
                    modal.find('#delete-form').css("display", "block")
                    modal.find('.vendor-id').val(id)
                    modal.find('.price').val(price)
                }
                else {
                    modal.find('#modal-body-text').html("Please ensure correct value is entered for price")
                    modal.find('#delete-form').css("display", "none")
                }

            });

            $('#edit-vendor').on('show.bs.modal', function (event) {
                var button = $(event.relatedTarget)
                var id = button.data('vendorid')
                var name = button.data('brandname')
                var price = $('#price-for-' + id).html()
                //console.log('price => ' + price)
                //console.log("name => " + name)
                /*console.log("id => "+ id)
                console.log("name => " + name)
                console.log("count => " + count)*/
                //modal.find('#subName').html(name)
                var modal = $(this)
                if (price > 100) {
                    modal.find('#modal-body-text').html("Are you sure you would like to submit changes for <strong>" + name + "</strong> ?")
                    modal.find('#delete-form').css("display", "block")
                    modal.find('.vendor-id').val(id)
                    modal.find('.price').val(price)
                }
                else {
                    modal.find('#modal-body-text').html("Please ensure correct value is entered for price")
                    modal.find('#delete-form').css("display", "none")
                }

            });

        });
    </script>
}

500Dishes/Views/Admin/AllWithdrawals.cshtml
@model PagedList.IPagedList<_500Dishes.Models.Transaction>
@using PagedList.Mvc;

@{
    ViewBag.Title = "AllWithdrawals";
    Layout = "~/Views/Shared/_AdminLayoutPage.cshtml";
}

<h2>AllWithdrawals</h2>

@if (TempData["WithdrawalMessage"] != null)
{
    <div class="alert alert-danger alert-dismissable" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @TempData["WithdrawalMessage"].ToString()
    </div>
}

<table class="table">
    <tr>
        <th>
            Vendor
        </th>
        <th>
            Amount
        </th>
        <th>
            Extra Text
        </th>
        <th>
            Date
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Vendor.FirstName)
            <br />
            @Html.DisplayFor(modelItem => item.Vendor.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Amount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ExtraText)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @*@Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })*@
        </td>
    </tr>
}
</table>

<div class="container">
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of
    @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("AllWithdrawals", new { page }))
</div>

500Dishes/Views/Admin/CreateSubscription.cshtml
@model _500Dishes.Models.SubscriptionPlan

@{
    ViewBag.Title = "Subscriptions";
    Layout = "~/Views/Shared/_AdminLayoutPage.cshtml";
}

<h2>Create Subscription</h2>
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NoOfMeals, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NoOfMeals, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoOfMeals, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DrinksPerMeal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                    @Html.EditorFor(model => model.DrinksPerMeal, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DrinksPerMeal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

500Dishes/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayoutPage.cshtml";
}

<h2>Index</h2>

500Dishes/Views/Admin/Order.cshtml
@model _500Dishes.Models.Order

@{
    ViewBag.Title = "Order";
    Layout = "~/Views/Shared/_AdminLayoutPage.cshtml";
}

<h2>Order</h2>

<div>
    <dl class="dl-horizontal">
        <dt>
            Customer Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.Name)
        </dd>

        <dt>
            Meal
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Meal.Name)
        </dd>
        <dt>
            Vendor
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vendor.BrandName)
        </dd>
        <dt>
            Delivery Address
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt>
            Phone
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt>
            Alternate Phone
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AltPhone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt>
            Review
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Review.Text)
        </dd>

    </dl>
</div>
@*<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.OrderID }) |
    @Html.ActionLink("Back to List", "Index")
</p>*@