500Dishes/Controllers/PayStackEventsController.cs
using _500Dishes.Misc;
using _500Dishes.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
//using System.Web.Http; 

namespace _500Dishes.Controllers
{
    public class PayStackEventsController : Controller
    {
        // GET: PayStackEvents
        [HttpPost]
        public string Index()
        {
            System.IO.Stream req = Request.InputStream;
            req.Seek(0, System.IO.SeekOrigin.Begin);
            string json = new System.IO.StreamReader(req).ReadToEnd();
            EventObject eventObject = Newtonsoft.Json.JsonConvert.DeserializeObject<EventObject>(json);

            if (eventObject == null)
                return "null ish";

            switch (eventObject.@event)
            {
                case "subscription.create":
                    new Task(() => { createSubscriptionAync(eventObject.data); }).Start();
                    //createSubscriptionAync(eventObject);
                    break;

                case "subscription.disable":
                    new Task(() => { disableSubscriptionAync(eventObject.data); }).Start();
                    break;

                case "subscription.enable":
                    new Task(() => { enableSubscriptionAync(eventObject.data); }).Start();
                    break;
            }
            //return new HttpStatusCodeResult(HttpStatusCode.OK);
            return "event => " + eventObject.@event + " event amount => " + eventObject.data.amount;
        }

        [HttpPost]
        public async Task<ActionResult> EventManager(/*RootObject eventObject*/)
        {

            System.IO.Stream req = Request.InputStream;
            req.Seek(0, System.IO.SeekOrigin.Begin);

            string json = new System.IO.StreamReader(req).ReadToEnd();
            //StripeEvent stripeEvent = null;

            EventObject eventObject = Newtonsoft.Json.JsonConvert.DeserializeObject<EventObject>(json);

            if (eventObject == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            switch (eventObject.@event)
            {
                case "subscription.create":
                    //new Task(() => { createSubscriptionAync(eventObject.data); }).Start();
                    await createSubscriptionAync(eventObject.data);
                    break;

                case "subscription.disable":
                    //new Task(() => { disableSubscriptionAync(eventObject.data); }).Start();
                    await disableSubscriptionAync(eventObject.data);
                    break;

                case "subscription.enable":
                    //new Task(() => { enableSubscriptionAync(eventObject.data); }).Start();
                    await enableSubscriptionAync(eventObject.data);
                    break;
                case "invoice.create":
                    await createInvoiceForSubscriptionAync(eventObject.data);
                    break;
                case "invoice.update":
                    await enableInvoiceForSubscriptionAync(eventObject.data);
                    break;
            }
            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        private async Task enableInvoiceForSubscriptionAync(Data data)
        {
            if (data.paid && data.status == "success")
            {
                using (DataContext db = new DataContext())
                {
                    var customer = db.Users.SingleOrDefault(x => x.CustomerCode == data.customer.customer_code);
                    if (customer != null)
                    {
                        var prevSub = await db.UserSubscriptions.Where(x => x.UserID == customer.UserID && x.Enabled && !x.Deleted).OrderByDescending(x => x.EndDate).FirstAsync();
                        if (prevSub != null)
                            await disableSubscriptionAyncMethod(customer.CustomerCode, prevSub.SubscriptionCode, prevSub.SubPlan.PlanCode);

                        var userSub = db.UserSubscriptions.SingleOrDefault(x => x.SubscriptionCode == data.subscription.subscription_code);
                        if (userSub != null && !userSub.Enabled)
                        {
                            userSub.Enabled = true;
                            userSub.Token = await PayStackAPI.FetchSubscription(data.subscription.subscription_code);
                            userSub.StartDate = DateTime.UtcNow.AddHours(1);
                            userSub.EndDate = DateTime.UtcNow.AddHours(1).AddDays(6);
                            db.Entry(userSub).State = System.Data.Entity.EntityState.Modified;
                            customer.SubscriptionPlanID = userSub.SubPlan.ID;
                            db.Entry(customer).State = System.Data.Entity.EntityState.Modified;
                            await db.SaveChangesAsync();
                        }
                    }
                }
            }
        }

        private async Task createInvoiceForSubscriptionAync(Data data)
        {
            using (DataContext db = new DataContext())
            {
                var customer = db.Users.SingleOrDefault(x => x.CustomerCode == data.customer.customer_code);
                if (customer != null)
                {
                    var userSub = await db.UserSubscriptions.Include(x => x.SubPlan).Where(x => x.UserID == customer.UserID && x.Enabled && !x.Deleted).OrderByDescending(x => x.EndDate).FirstOrDefaultAsync();
                    if (userSub != null)
                    {
                        var newSub = new UserSubscription()
                        {
                            UserID = customer.UserID,
                            StartDate = DateTime.UtcNow.AddHours(1),
                            SubID = userSub.SubPlan.ID,
                            SubscriptionCode = data.subscription.subscription_code
                        };

                        customer.SubscriptionPlanID = userSub.SubPlan.ID;
                        db.UserSubscriptions.Add(newSub);
                        db.Entry(customer).State = System.Data.Entity.EntityState.Modified;                        
                        await db.SaveChangesAsync();
                    }
                }
            }
        }

        private async Task createSubscriptionAync(Data responseData)
        {
            string customerCode = responseData.customer.customer_code;
            string subCode = responseData.subscription_code;
            string planCode = responseData.plan.plan_code;

            await createSubAsyncMethod(customerCode, subCode, planCode);
            await enableSubscriptionAync(responseData);
        }

        private async Task createSubAsyncMethod(string customerCode, string subCode, string planCode)
        {
            using (DataContext db = new DataContext())
            {
                var customer = db.Users.SingleOrDefault(x => x.CustomerCode == customerCode);
                if (customer != null)
                {
                    var oldPlan = await db.UserSubscriptions.Include(x => x.SubPlan).Where(x => x.UserID == customer.UserID && x.Enabled ==  true && x.Deleted == false).OrderByDescending(x => x.EndDate).FirstOrDefaultAsync();
                    if (oldPlan != null)
                        await disableSubscriptionAyncMethod(customerCode, oldPlan.SubscriptionCode, oldPlan.SubPlan.PlanCode);

                    var subPlan = db.SubscriptionPlans.SingleOrDefault(x => x.PlanCode == planCode);
                    if (subPlan != null)
                    {
                        var newSub = new UserSubscription()
                        {
                            UserID = customer.UserID,
                            StartDate = DateTime.UtcNow.AddHours(1),
                            SubID = subPlan.ID,
                            SubscriptionCode = subCode
                        };

                        customer.SubscriptionPlanID = subPlan.ID;
                        db.Entry(customer).State = System.Data.Entity.EntityState.Modified;
                        db.UserSubscriptions.Add(newSub);
                        await db.SaveChangesAsync();
                    }
                }
            }
        }

        private async Task disableSubscriptionAync(Data responseData)
        {
            string customerCode = responseData.customer.customer_code;
            string subCode = responseData.subscription_code;
            string planCode = responseData.plan.plan_code;

            await disableSubscriptionAyncMethod(customerCode, subCode, planCode);
        }

        private async Task disableSubscriptionAyncMethod(string customerCode, string subCode, string planCode)
        {
            using (DataContext db = new DataContext())
            {
                var customer = db.Users.SingleOrDefault(x => x.CustomerCode == customerCode);
                if (customer != null)
                {
                    var subPlan = db.SubscriptionPlans.SingleOrDefault(x => x.PlanCode == planCode);
                    if (subPlan != null)
                    {
                        var userSub = db.UserSubscriptions.SingleOrDefault(x => x.SubscriptionCode == subCode && x.SubID == subPlan.ID && x.UserID == customer.UserID);
                        userSub.Deleted = true;
                        db.Entry(userSub).State = System.Data.Entity.EntityState.Modified;
                        await db.SaveChangesAsync();
                    }
                }
            }
        }

        private async Task enableSubscriptionAync(Data responseData)
        {
            string customerCode = responseData.customer.customer_code;
            string subCode = responseData.subscription_code;
            string planCode = responseData.plan.plan_code;

            await enableSubAsyncMethod(customerCode, subCode, planCode);
        }

500Dishes/Views/Customer/AddSubscription.cshtml
@model _500Dishes.Models.SubscriptionsViewModel

@{
    ViewBag.Title = "AddSubscription";
    Layout = "~/Views/Shared/_ClientLayoutPage.cshtml";
}

@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Html.Raw(TempData["SuccessMessage"] as string)
    </div>
}
@if (TempData["UserSubscriptionMessage"] != null)
{
    <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Html.Raw(TempData["UserSubscriptionMessage"] as string)
    </div>
}
@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Html.Raw(TempData["ErrorMessage"] as string)
    </div>
}
@*<p class="text-success success">@ViewBag.SuccessMessage</p>
<p class="text-danger danger">@ViewBag.ErrorMessage</p>*@
    
@if (Model.UserSub != null)
{
    <div>
        <h3>Current Subscription</h3>
        <dl class="dl-horizontal">
            <dt>Name : </dt>
            <dd>@Model.UserSub.SubPlan.Name</dd>
            <dt>Amount : </dt>
            <dd>@Html.Raw("&#8358; ") @(Model.UserSub.SubPlan.Amount.ToString("N"))</dd>
            <dt>Start Date : </dt>
            <dd>@Model.UserSub.StartDate.Value.ToString("dd-MM-yyyy")</dd>
            <dt>End Date : </dt>
            <dd>@((Model.UserSub.EndDate) == null ? "" : Model.UserSub.EndDate.Value.ToString("dd-MM-yyyy")) </dd>
        </dl>
    </div>
    <hr />
}

<h3>All Subscription Plans</h3>
<table class="table table-condensed table-hover table-responsive">
    <tr>
        <th>
            Name
        </th>
        <th>
            Amount
        </th>
        <th>
            Description
        </th>
        <th>
            Meals/Day
        </th>
        <th>
            Drinks/Meal
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.AllPlans)
        {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            &#8358; @item.Amount.ToString("N")
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NoOfMeals)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DrinksPerMeal)
        </td>
        <td>
            @if (Model.UserSub != null && item.ID == Model.UserSub.SubID)
            {
                <span class="text-success">Subscribed</span>
                
                if (!Model.UserSub.Enabled) { 
                    using (Html.BeginForm("EnableSubscription", "Customer", new { userSubID = Model.UserSub.ID, subID = Model.UserSub.SubID }, FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        <input type="submit" value="Activate Subscription" class="btn btn-default" />
                    }
                    @*@Html.ActionLink("Activate Subscription", "EnableSubscription", new { subID = @Model.UserSub.SubID }, new { @class= "btn btn-default"} )*@
                }
            }
            else { 
            <a data-toggle="modal" href="#new-subscription" class="btn btn-info" data-subid="@item.ID" data-subname="@item.Name">Subscribe</a>
            }
        </td>
    </tr>
}

</table>

@*<input type="button" value="Click To Test" onclick="submitForm()" />*@

@section Scripts {
    <script type="text/javascript">
    $(function () {
        $('#new-subscription').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget)
            var id = button.data('subid')
            var name = button.data('subname')
            console.log("id => "+ id)
            console.log("name => " + name)
            var modal = $(this)
            modal.find('.subscription-id').val(id)
            modal.find('#subName').html(name)
        });
    });
    @*function submitForm() {
        var roles = {
            "event": "subscription.create",
            "data": {
                "domain": "test",
                "status": "active",
                "subscription_code": "SUB_vsyqdmlzble3uii",
                "amount": 50000,
                "cron_expression": "0 0 28 * *",
                "next_payment_date": "2016-05-19T07:00:00.000Z",
                "open_invoice": null,
                "createdAt": "2016-03-20T00:23:24.000Z",
                "plan": {
                    "name": "Monthly retainer",
                    "plan_code": "PLN_gx2wn530m0i3w3m",
                    "description": null,
                    "amount": 50000,
                    "interval": "monthly",
                    "send_invoices": true,
                    "send_sms": true,
                    "currency": "NGN"
                },
                "authorization": {
                    "authorization_code": "AUTH_96xphygz",
                    "bin": "539983",
                    "last4": "7357",
                    "exp_month": "10",
                    "exp_year": "2017",
                    "card_type": "MASTERCARD DEBIT",
                    "bank": "GTBANK",
                    "country_code": "NG",
                    "brand": "MASTERCARD"
                },
                "customer": {
                    "first_name": "BoJack",
                    "last_name": "Horseman",
                    "email": "bojack@horsinaround.com",
                    "customer_code": "CUS_xnxdt6s1zg1f4nx",
                    "phone": "",
                    "metadata": {}
                }
            }
        };

        jQuery.ajax({
            type: "POST",
            url: "@Url.Action("EventManager", "PayStackEvents")",
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(roles),
                    success: function (data) { alert(data); },
                    failure: function (errMsg) {
                        alert(errMsg);
                    }
                });

                var url ="@Url.Action("EventManager", "PayStackEvents")";
                console.log("url => " + url);

            }*@

    </script>
}



<div class="modal fade" id="new-subscription" aria-hidden="true" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h2 class="modal-title text-center text-danger">Subscription</h2>
            </div>
            <div class="modal-body">
                <p class="text-center">Are you sure you want to subscribe to <strong><span class="text-danger" id="subName"></span></strong></p>
                @using (Html.BeginForm("AddSubscription", "Customer", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <input type="hidden" name="subID" class="subscription-id">
                    <button type="submit" class="btn btn-primary text-uppercase">Submit</button>
                }
            </div>
        </div>
    </div>
</div>

500Dishes/Views/Customer/ConfirmOrder.cshtml
@model _500Dishes.Models.OrderViewModel

@{
    ViewBag.Title = "ConfirmOrder";
    Layout = "~/Views/Shared/_ClientLayoutPage.cshtml";
}

<h2>ConfirmOrder</h2>

<div>
    <p class="text-primary">Place order for <em>@ViewBag.MealName</em></p>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.HiddenFor(x => x.CustomerID)
        @Html.HiddenFor(x => x.MealID)
        @Html.HiddenFor(x => x.VendorID)

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">+234</span>
                    @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control", style = "max-width: 225px;" } })
                </div>
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AltPhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">+234</span>
                    @Html.EditorFor(model => model.AltPhone, new { htmlAttributes = new { @class = "form-control", style = "max-width: 225px;" } })
                </div>
                @Html.ValidationMessageFor(model => model.AltPhone, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

500Dishes/Views/Customer/EditPassword.cshtml
@model _500Dishes.Models.EditPasswordViewModel

@{
    ViewBag.Title = "EditPassword";
    Layout = "~/Views/Shared/_ClientLayoutPage.cshtml";
}

<h2>Edit Password</h2>
@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @(TempData["SuccessMessage"] as string)
    </div>
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            @Html.LabelFor(model => model.NewPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NewPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NewPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Edit Password" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

500Dishes/Views/Customer/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_ClientLayoutPage.cshtml";
}

<h2>Index</h2>

500Dishes/Views/Customer/MyAccount.cshtml
@model _500Dishes.Models.UserViewModel

@{
    ViewBag.Title = "MyAccount";
    Layout = "~/Views/Shared/_ClientLayoutPage.cshtml";
}

<h2>MyAccount</h2>

@if (TempData["MyAccountSuccess"] != null)
{
    <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @(TempData["MyAccountSuccess"] as string)
    </div>
}
@if (TempData["MyAccountError"] != null)
{
    <div class="alert alert-dismissable alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @(TempData["MyAccountError"] as string)
    </div>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">               
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*<div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">+234</span>*@
                    @*<input type="text" name="Phone" id="Phone" class="form-control" aria-describedby="basic-addon1">*@
                    @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control", style = "max-width: 225px;" } })
                @*</div>*@
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @readonly="readonly" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Subscription Plan", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.DisplayFor(model => model.SubName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SubName, "", new { @class = "text-danger" })*@
                <span class="lead">@Model.SubName</span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

500Dishes/Views/Customer/OrderMeal.cshtml
@model PagedList.IPagedList<_500Dishes.Models.Meal>
@using PagedList.Mvc;

@{
    ViewBag.Title = "OrderMeal";
    Layout = "~/Views/Shared/_ClientLayoutPage.cshtml";
}

@if (TempData["SubscriptionError"] != null)
{
    <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @(TempData["SubscriptionError"] as string)
    </div>
}
@if (TempData["MealSuccess"] != null)
{
    <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @(TempData["MealSuccess"] as string)
    </div>
}


<h2>OrderMeal</h2>

@using (Html.BeginForm("OrderMeal", "Customer", FormMethod.Get))
{
    <div class="form-group">
        <label class="sr-only">Search</label>
        @Html.TextBox("searchString", ViewBag.CurrentFilter as string, new { @class = "form-control input-lg", placeholder = "Enter a search term here...", type = "search" })
    </div>
}

@foreach (var item in Model)
    {
<div class="col-sm-4 col-xs-6">
    <div class="panel panel-default">
        <div class="panel-heading">
            <img src="~/Images/Meals/@item.ImagePath" class="img-responsive" style="height: 200px;" />
        </div>
        <div class="panel-body">
            <div>
                <span class="lead text-muted">@item.Name</span><br />
                @item.Description
                <br />
                @*@Html.ActionLink("Pick", "AddMeal", "Customer", new { id = @item.ID }, new { @class = "btn btn-default" })
                    <br />*@
                <div style="display:block">
                    <img class="img-responsive pull-left" style="width:40px; height:40px; margin-right: 20px;" src="~/Images/Vendors/@item.Vendor.ImagePath" />
                    <div>
                        <span class="text-danger">@item.Vendor.BrandName</span>
                        <br />
                        <span>
                            Rating--
                            @if (item.Reviews.Count > 0)
                            { @item.GetRating();
                            }
                        </span>
                    </div>
                </div>
                <br />
                @Html.ActionLink("Order", "OrderMeal", "Customer", new { id = @item.ID }, new { @class = "btn btn-info" })
            </div>
        </div>
    </div>
</div>
    <span class="clearfix"></span>
    }

<div class="container">
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of
    @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("OrderMeal", new { page }))
</div>